export const DELIVERY_DI_TOKEN = {
  NOTIFICATION_DELIVERY_SERVICE: Symbol('NOTIFICATION_DELIVERY_SERVICE'),
  EMAIL_DELIVERY_SERVICE: Symbol('EMAIL_DELIVERY_SERVICE'),
  WEB_DELIVERY_SERVICE: Symbol('WEB_DELIVERY_SERVICE'),
  MOBILE_DELIVERY_SERVICE: Symbol('MOBILE_DELIVERY_SERVICE'),
  SMS_DELIVERY_SERVICE: Symbol('SMS_DELIVERY_SERVICE'),
};
